### ISSUE TITLE
[REQUEST]: Any chance to get it as commandline ool?

### ISSUE THREAD

**Issue by Woisek** [Markavian/tile-merger#2]
I would love to use this tool from command line to merge multiple given images. Would that be possible somehow? 🙂

**Comment by johnbeech** [comment]
@Woisek yes I could make this work via a command line;

- What operating system are you currently using?
- What types of command would you want to run?

I'll take a look and see what might be possible.

**Comment by Woisek** [comment]
Hey cool! 👍
Well, I'm using Win10 64Bit and basically I think it would help to have:
src dir
target dir
Nr of Cols
direction
and an extra one: images

My idea is, to have a script that feeds selected images into tilemerger.exe. I can imagine an example like:
Using only folders:
tilemerger.exe --srcdir="sourcedirectory" --destdir="destinationdir" -nrcol=6 --td=lr

My main usage would be with giving files instead of a source directory:
tilemerger.exe --destdir="destinationdir" -nrcol=6 --td=lr --imgs="[list-of-multiple-images]"

With this, I could select multiple images in an folder and let tilemerger merge them and save the collage in the very same folder.
That would be incredible handy. 😄

**Comment by Woisek** [comment]
@johnbeech Any news on the commandline tool? 🙂

**Comment by johnbeech** [comment]
Thanks for chasing... I got some time this evening to look into it. First problem was getting the project to load in Visual Studio, but I think I've succeeded there at least:

![image](https://github.com/Markavian/tile-merger/assets/6341696/a77b7624-3c7d-4aa5-a2c8-2fd656e80c5b)

**Comment by Woisek** [comment]
Cool! I hope you can finish it. I'm _very_ looking forward to it ... 😁👍

**Comment by johnbeech** [comment]
@Woisek finalised my dev and testing this evening, here you go:

- https://github.com/Markavian/tile-merger/releases/tag/1.0.0

README has sample commands with examples:
- https://github.com/Markavian/tile-merger#example-commands

Any bugs let me know... I'll try and jump straight on them!

**Comment by Woisek** [comment]
Woho! 🎉🎉 Will test it and then give feedback. Thanks!!

**Comment by Woisek** [comment]
@johnbeech 
UPDATE:
Works very good, but I have found, that if a filename has an equal sign = it won't work, meaning it apparently cuts the name and finds no image.
For example:
00004-S=2938454962-St=40-Sa=DPM++ 2M Karras-Cfg=8.png

Oh, and maybe you could make it possible to set a default output name without the need for a destination path?
Again, many, many thanks for this great and helpful tool! 😁😁🎉🎉🎉🎉
