### ISSUE TITLE
Improper File Name sort order beyond 9

### ISSUE THREAD

**Issue by gcou** [Markavian/tile-merger#4]
If a file name is F1, F2, ... F9, F10, F11, F12, Windows Explorer and FastStone Image viewer knows how to sort it correctly.  So F10 comes after F9.

But Tile Merger sorts F10 to F19 after F1 instead of after F9.  As a manual workaround, I have to rename F10 to Fa and F11 to Fb manually before I can use Tile Merger.

Is it possible to fix this issue?

**Comment by XtheOne** [comment]
I fixed this in 2017, I could create a pull request if it still works on the new version.

**Comment by Markavian** [comment]
Sorry I've been busy for a few weeks now; definitely something that can be fixed. @XtheOne if you've got time... that would be much appreciated, will add you to the credits.

**Comment by XtheOne** [comment]
I just created a pull request.
Maybe gcou can do the testing and let us know if it works.

**Comment by johnbeech** [comment]
See #5 - I've just completed some testing. Will start preparing a release.

**Comment by johnbeech** [comment]
@gcou released version 1.1.0 if you could check and see if it fixes your issue:

- https://github.com/Markavian/tile-merger
- https://github.com/Markavian/tile-merger/releases/tag/1.1.0
